name: clerk
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  http: ^0.13.4
  socket_io: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
