name: clerk
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  get_server: ^1.1.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
